/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameIndexRouteImport } from './routes/$game/index'
import { Route as GameGuideRouteImport } from './routes/$game/$guide'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/$game/',
  path: '/$game/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGuideRoute = GameGuideRouteImport.update({
  id: '/$game/$guide',
  path: '/$game/$guide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$game/$guide': typeof GameGuideRoute
  '/$game/': typeof GameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$game/$guide': typeof GameGuideRoute
  '/$game': typeof GameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$game/$guide': typeof GameGuideRoute
  '/$game/': typeof GameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$game/$guide' | '/$game/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$game/$guide' | '/$game'
  id: '__root__' | '/' | '/$game/$guide' | '/$game/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameGuideRoute: typeof GameGuideRoute
  GameIndexRoute: typeof GameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$game/': {
      id: '/$game/'
      path: '/$game'
      fullPath: '/$game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$game/$guide': {
      id: '/$game/$guide'
      path: '/$game/$guide'
      fullPath: '/$game/$guide'
      preLoaderRoute: typeof GameGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameGuideRoute: GameGuideRoute,
  GameIndexRoute: GameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
